---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    fig.path = "man/figures/README-",
    out.width = "100%"
)
```

# FindIT2

<!-- badges: start -->
<!-- badges: end -->

The goal of `FindIT2` is to ...

## Installation instructions

Get the latest stable `R` release from [CRAN](http://cran.r-project.org/). Then install `FindIT2` using from [Bioconductor](http://bioconductor.org/) the following code:

```{r 'install', eval = FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}

BiocManager::install("FindIT2")
```

And the development version from [GitHub](https://github.com/shangguandong1996/FindIT2) with:

```{r 'install_dev', eval = FALSE}
BiocManager::install("shangguandong1996/FindIT2")
```


## Document
To view documentation of FindIT2, start R and enter:
```{r, eval = FALSE}
browseVignettes("FindIT2")
```
